### ISSUE TITLE
Dynamic imports with aliases not working running under Windows OS

### ISSUE THREAD

**Issue by abuenoinn** [vite-plugin/vite-plugin-dynamic-import#13]
The plugin is not working when using aliases in imports under Windows, but it's working in Mac OS and Linux.

This is the error: `[plugin:vite-plugin-dynamic-import] invalid import "import('@/components/${path}${name}.vue')". Variable bare imports are not supported, imports must start with ./ in the static part of the import. For example: import('./foo/${bar}.js').`

vite.config.ts:

`resolve: {
      alias: {
        '@': resolve(__dirname, './src'),
      },
    },`

Node: 16.15.1
Vite: 2.9.9
vite-plugin-dynamic-import: 0.9.9
OS: Windows 10

**Comment by caoxiemeihao** [comment]
You can provide complete configuration?

**Comment by abuenoinn** [comment]
![vite config](https://user-images.githubusercontent.com/108515769/176863758-ca9e04d9-9267-44b8-8688-a4d34fb2b6ec.png)

In dynamic-import-to-glob I make this change for testing:
`if ((!glob.startsWith('./') && !glob.startsWith('../')) && (!glob.startsWith('.\\') && !glob.startsWith('..\\'))) {`

The problem is in Windows path is like '..\..\..\components\etc...'

**Comment by caoxiemeihao** [comment]
You can try wrapping a `normalizePath()`

```js
import { normalizePath } from 'vite'

resolve: { alias: { '@': normalizePath(resolve(__dirname, './src')), }, },
```

**Comment by abuenoinn** [comment]
Is getting the same error

![image](https://user-images.githubusercontent.com/108515769/176874749-3f04763a-c321-4f16-b126-8b0647c21aed.png)

**Comment by chumager** [comment]
It also happens to me with Linux debian.
```sh
[vite-plugin-dynamic-import] invalid import "import(`@/${comp}`)". Variable bare imports are not supported, imports must start with ./ in the static part of the import. For example: i
mport(`./foo/${bar}.js`).
```
vite.config.js:
```js
import {createVuePlugin} from "vite-plugin-vue2";
import viteCompression from "vite-plugin-compression";
import dynamicImport from "vite-plugin-dynamic-import";
import {defineConfig, normalizePath} from "vite";
import path from "path";
import fs from "fs";

const HOST = "0.0.0.0";

import JSON5 from "json5";
import YAML from "yaml";
const baseConfig = YAML.parse(fs.readFileSync("/etc/default/itdfw.yaml", {encoding: "utf8"}));
const {config: configDir, fileType} = baseConfig;
const configPath = path.resolve(configDir, `config.${fileType}`);
const configFile = fs.readFileSync(configPath, {encoding: "utf8"});
let configObj;
switch (fileType) {
  case "yaml":
    configObj = YAML.parse(configFile);
    break;
  case "json":
    configObj = JSON.parse(configFile);
    break;
  case "json5":
    configObj = JSON5.parse(configFile);
    break;
  case "js":
    configObj = require(configPath);
    break;
  default:
    throw new Error("fileType unknown, pleas check fileType key in /etc/default/itdfw.yaml");
}
let itdConfig = {};
try {
  itdConfig = require(path.resolve(process.cwd(), "../.itdfw.js"));
} catch (e) {
  console.warn(".itdfw.js doesn't exist");
}
let protocol;
switch (configObj.Protocol) {
  case "H2":
  case "SPDY":
  case "HTTP2":
  case "HTTPS":
    protocol = "https";
    break;
  case "HTTP":
  default:
    protocol = "http";
}
process.env.VUE_APP_PROTOCOL = protocol;
const proxy = `${protocol}://${itdConfig.devHost || process.env.VUE_APP_HOST}`;
console.log("proxy:", proxy);
const {DocumentRoot} = baseConfig;
const config = defineConfig({
  base: "./",
  server: {
    host: HOST,
    proxy: {
      "/APP": {
        target: proxy,
        changeOrigin: true
      }
    }
  },
  resolve: {
    alias: [
      {
        find: "@/",
        replacement: normalizePath(path.resolve(__dirname, "src"))
      },
      {
        find: "itdfw/",
        replacement: path.resolve(__dirname, "src")
      },
      {
        find: /^ITDFW$/,
        replacement: path.resolve(__dirname)
      },
      {
        find: "default/",
        replacement: path.resolve(DocumentRoot, "DEFAULT/vue/src")
      }
    ]
  },
  plugins: [
    dynamicImport(),
    createVuePlugin({
      template: {
        compilerOptions: {
          isCustomElement: tag => tag.includes("itd-wc")
        }
      }
    }),
    viteCompression()
  ],
  build: {
    outDir: "../html"
  }
});
export default config;
```
node: 16.15.1
vite: 2.9.13
rollup: 2.75.6
vite-plugin-dynamic-import: 0.9.9

**Comment by caoxiemeihao** [comment]
@chumager thanks for your feedback. Can you provide a minimize Demo?

**Comment by GKhelio** [comment]
I managed to fix it by adding the `normalizePath` to the following two paths 

`index.ts`
![image](https://user-images.githubusercontent.com/22683120/177087021-4a2e9c3c-022c-456e-97b0-7d49b89a817b.png)

`dynamic-import-to-glob.ts`
![image](https://user-images.githubusercontent.com/22683120/177087256-eb3ad5f3-bf31-4698-9c92-3103d25ee7d2.png)

**Comment by GKhelio** [comment]
@caoxiemeihao A new version will be generated??

**Comment by caoxiemeihao** [comment]
@GKhelio coming soon...

**Comment by caoxiemeihao** [comment]
Now, `vite-plugin-dynaimc-import` [![NPM version](https://img.shields.io/npm/v/vite-plugin-dynamic-import.svg)](https://npmjs.org/package/vite-plugin-dynamic-import) has been available.
