### ISSUE TITLE
dynamic require of "../../components/ColorPicker" is not supported

### ISSUE THREAD

**Issue by ashergaga** [vite-plugin/vite-plugin-dynamic-import#16]
![c19d61c9466fe5ecf4bd334ebadb72c](https://user-images.githubusercontent.com/26506373/177123679-c273695f-84fa-4eda-bf6f-3eb4b6497379.jpg)
![1030a5d3244a1b9ef84c99df00af548](https://user-images.githubusercontent.com/26506373/177123709-81146774-a5e6-42d0-b57c-5933a474c11f.jpg)

Can this plugin solve this error when using 'amis'?

**Comment by GKhelio** [comment]
@ashergaga  You are using aliases??

**Comment by caoxiemeihao** [comment]
This looks like from Webpack syntax. The feature is not supported on `vite-plugin-dynamic-import`.  
@youngleish  This feature should be implemented in the next version of [vite-require](https://github.com/vite-plugin/vite-require).
