### ISSUE TITLE
Ts import type incorrect I am not sure what cause

### ISSUE THREAD

**Issue by zq0904** [vite-plugin/vite-plugin-dynamic-import#21]
```ts
  // package.json
  "vite": "^3.0.0",
  "vite-plugin-dynamic-import": "^1.0.0",
```
```ts
// vite.config.ts
import dynamicImport from 'vite-plugin-dynamic-import'
plugins: [
    // @ts-expect-error
    dynamicImport.default(), // Does not match the document, and the TS prompt is incorrect
]
```
I don't know. Possible cause?
1. Is it just the wrong type of export?
2. allowSyntheticDefaultImports: true // Has nothing to do with this configuration
3. package.json "type": "module", // Does it matter?

**Comment by caoxiemeihao** [comment]
#### ESM import

```diff
plugins: [
    // @ts-expect-error
-    dynamicImport.default(), // Does not match the document, and the TS prompt is incorrect
+    dynamicImport(),
]
```

#### CJS require

```js
// vite.config.ts
const dynamicImport = require('vite-plugin-dynamic-import').default;

plugins: [
    dynamicImport(),
]
```

**Comment by zq0904** [comment]
> #### ESM 导入
> ```diff
> // vite.config.ts
> import dynamicImport from 'vite-plugin-dynamic-import'
> plugins: [
>     // @ts-expect-error
> -    dynamicImport.default(), // Does not match the document, and the TS prompt is incorrect
> +    dynamicImport(),
> ]
> ```
> 
> #### CJS 要求
> ```js
> // vite.config.ts
> const dynamicImport = require('vite-plugin-dynamic-import').default;
> 
> plugins: [
>     dynamicImport(),
> ]
> ```

An error is reported when esM is introduced in this version
// package.json
"Vite" : "^ 3.0.0",
"Vite - plugin - dynamic - import" : "^ 1.0.0",

dynamicImport is not a function
