### ISSUE TITLE
Uncaught Error: Module "fs" has been externalized for browser compatibility. Cannot access "fs.realpath" in client code.

### ISSUE THREAD

**Issue by caredev** [vite-plugin/vite-plugin-dynamic-import#26]
When importing the plugin I get
Uncaught Error: Module "fs" has been externalized for browser compatibility. Cannot access "fs.realpath" in client code.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/71512870/187032039-fcd97a49-5189-40ea-8b1b-1f60c692b67e.png">

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduce Demo?
