### ISSUE TITLE
默认导出不是一个函数

### ISSUE THREAD

**Issue by yibird** [vite-plugin/vite-plugin-dynamic-import#29]
在Vite3.x中 import dynamicImport from "vite-plugin-dynamic-import";  dynamicImport的值是一个对象,不是一个函数

**Comment by caoxiemeihao** [comment]
删掉 `"type": "module"` 即可，`"type": "module"` 将会在下个版本支持。

**Comment by caoxiemeihao** [comment]
[feat(🌱): support "type": "module"](https://github.com/vite-plugin/vite-plugin-dynamic-import/commit/5940444b62c10d671d9b663e98a38e5277228a7d)
