### ISSUE TITLE
How to have a dynamic import SVG component

### ISSUE THREAD

**Issue by SirMishaa** [vite-plugin/vite-plugin-dynamic-import#30]
Hello,

I have an issue when building the Vue (2.7) app: 
> [plugin:vite:dynamic-import-vars] invalid import "/icons/${this.name}.svg?raw". Variable absolute imports are not supported, imports must start with ./ in the static part of the import. For example: import(`./foo/${bar}.js`).

We're using this component everywhere in our application.
SwIcon.vue : 
```vue
<template lang="pug">
  div
    span.block(
      :class="[styleClass, sizeClass]"
      :style="{strokeLinecap: 'round', strokeLinejoin: 'round'}"
      @click="$emit('click')"
      v-html="svgRawContent"
    )
</template>

<script>
export default {
  name: 'SwIcon',
  props: {
    name: {
      type: String,
      default: '',
    },
    unstyled: {
      type: Boolean,
      default: false,
    },
    size: {
      type: String,
      default: 'w-6 h-6',
    },
  },
  data () {
    return {
      svgRawContent: '',
    };
  },
  computed: {
    sizeClass () {
      return this.size;
    },
    styleClass () {
      return this.unstyled ? '' : 'fill-none stroke-current stroke-2';
    },
  },
  // Todo: Replace by Suspense or something else when upgrading to Vue 3 to avoid async lifecycle method
  async mounted () {
    const svgObject = await import(`/icons/${this.name}.svg?raw`);
    this.svgRawContent = svgObject.default;
  },
};
</script>
``` 

Like you can see, we have this import ``await import(`/icons/${this.name}.svg?raw`);`` which is working good in development. 

I guess the problem comes from the fact that during the build phase, since it is dynamic, it is not able to bundle the svg since it does not know them. 

But then, **how can I keep a similar component and make it work?** Even if it has to bundle the whole icon's folder, it's not a big deal if it's lazy loaded.

Thanks in advance, I appreciate it ❤️

**Comment by SirMishaa** [comment]
Folder architecture is the following : 
![image](https://user-images.githubusercontent.com/42717232/187897578-dc0f46bc-0000-4dc8-9a70-7129452065e9.png)

Basically, SVG component is here : ``frontend/components/swComponents/SwIcon.vue``
Svg are in this folder: ``frontend/icons`` but we have some icons in subfolder, so ``frontend/car_discounts`` for example. (I think, that's maybe the tricky part) 


When I try to use relative import : 
```ts
await import(`../../icons/${this.name}.svg`)
```

I got the following error message :

>  Unknown variable dynamic import: ../../icons/car_discounts/car_lane_departure.svg

I think It's because the "name", is not a name, but sometime a path + name (yeah, bad naming, we're doing a lot of refactorings

**Comment by caoxiemeihao** [comment]
Thanks your feedback. Can you provide a minimal reproduction Demo? I will debug it.
