### ISSUE TITLE
Source map generation warning

### ISSUE THREAD

**Issue by archfz** [vite-plugin/vite-plugin-dynamic-import#32]
When building with vite, I get the following warning:

```text
WARN  Sourcemap is likely to be incorrect: a plugin (vite-plugin-dynamic-import) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction Demo?

**Comment by morleytatro** [comment]
Can we reopen this? Here's a repro:
https://github.com/morleytatro/sentry-dynamic-import

Going to cross post in Sentry's repo, as it seems the map does get created despite the warning.
