### ISSUE TITLE
Any chance for dynamic imports with absolute paths

### ISSUE THREAD

**Issue by hassanzohdy** [vite-plugin/vite-plugin-dynamic-import#37]
Hello,

I was wondering if there any chance to have this plugin work with dynamic import and absolute paths, that was really good to me when working with CRA, i suppose this is supported by webpack or so, but any idea of how getting this done.

Thanks in advance

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduce Demo?

**Comment by hassanzohdy** [comment]
@caoxiemeihao Any recommendations about it

**Comment by caoxiemeihao** [comment]
```diff
const aliases = {
- apps: "/src/apps",
+ apps: path.join(__dirname, "src/apps"),
};
```

Currently, `vite-plugin-dynamic-import` is based on file system paths, `/src/apps` will be treated  as the absolute path to the file, nott the root directory of the Vite project.
