### ISSUE TITLE
Dynamic not working Windows OS

### ISSUE THREAD

**Issue by GGBeng1** [vite-plugin/vite-plugin-dynamic-import#38]
version 1.1.0  is ok
<img width="517" alt="image" src="https://user-images.githubusercontent.com/40552498/200729030-7b92f8ed-e0ed-4b8b-9d04-26d269a24319.png">
version 1.2.3  path change
<img width="571" alt="image" src="https://user-images.githubusercontent.com/40552498/200729736-d04ee524-28ba-4b63-9c31-677201829316.png">

**Comment by caoxiemeihao** [comment]
Hi! 👋
Can you provide a minimal reproduction Deom? 👀

**Comment by GGBeng1** [comment]
> Hi! 👋 Can you provide a minimal reproduction Deom? 👀

https://github.com/GGBeng1/dynamic-import-miniapp
Only windows is faulty, macos or linux is not 😂

**Comment by moosemanf** [comment]
why did you close the ticket? Same here 1.2.3 does not work on Windows, 1.1.0 does...!

**Comment by GGBeng1** [comment]
> why did you close the ticket? Same here 1.2.3 does not work on Windows, 1.1.0 does...!
reopen now👀
