### ISSUE TITLE
🐞: `import(node_modules/xxx)`  not works

### ISSUE THREAD

**Issue by annabe1la** [vite-plugin/vite-plugin-dynamic-import#4]
while using dynamicImports , if .ts used 'a: Types',  throw an error
[vite] Internal server error: Unexpected token 
```ts
import { ReportHandler } from 'web-vitals';

export const reportWebVitals = (onPerfEntry?: ReportHandler) => {
  if (onPerfEntry && onPerfEntry instanceof Function) {
    import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
      getCLS(onPerfEntry);
      getFID(onPerfEntry);
      getFCP(onPerfEntry);
      getLCP(onPerfEntry);
      getTTFB(onPerfEntry);
    });
  }
};
 ```

**Comment by annabe1la** [comment]
it happens when u use type annotation, when I removed the annotation, the parser error will be gone

**Comment by caoxiemeihao** [comment]
I've tried to run it in my test, and it looks works normally

---

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/26263658/170433620-8c08b9e7-6ad6-4709-81ca-596060c1eb89.png">

--

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26263658/170433853-d19c31ad-2502-4f45-8d40-045074dd8892.png">

**Comment by annabe1la** [comment]
show your my code https://github.com/annabe1la/vite-plugin-dynamic-import/tree/playground
![357041653549663_ pic](https://user-images.githubusercontent.com/39275172/170439011-8acb560b-d68a-4c15-9464-f16485a1d1e7.jpg)
![357051653549721_ pic](https://user-images.githubusercontent.com/39275172/170439046-dada67f0-1eda-477f-af18-f7c9d71b1db7.jpg)

**Comment by caoxiemeihao** [comment]
This is really a 🐞. I think I can fix it tomorrow! 😄

**Comment by annabe1la** [comment]
bravo & grazie
