### ISSUE TITLE
支持图片等静态资源导入吗 | Support image or others static assets?

### ISSUE THREAD

**Issue by usercao** [vite-plugin/vite-plugin-dynamic-import#5]
例如 Webpack 的 `require()` 这种  
Like Webpack `require()`, it's can load any static assets

**Comment by caoxiemeihao** [comment]
你配置下 `vite.config.ts` 中的 `resolve.extensions` 试试

**Comment by usercao** [comment]
`require()`有两种应用场景

**Comment by caoxiemeihao** [comment]
一样的，插件不分  js、jsx 的

**Comment by usercao** [comment]
Demo地址 [ice-test](https://github.com/usercao/ice-test/blob/main/src/pages/Home/index.tsx#L57)

暂时考虑到4种引入方式(可能还有css/json等等?)，现在在用`vite-plugin-require`来引入，难点与本plugin想解决的问题一样不支持别名，希望测试下`build`的时候会不会出问题，因为Vite很多时候`dev`和`build`结果不一致。

**Comment by caoxiemeihao** [comment]
你这个想法是 vite-plugin-dynamic-require 你说的插件和我现在这个插件都不是干你这个的，搞清楚 :)

**Comment by usercao** [comment]
主要是并没有找到`vite-plugin-dynamic-require`相关的插件，只能用相似功能的替代，👌谢谢解答。

**Comment by caoxiemeihao** [comment]
开个插件也不难，要不要请我喝杯咖啡 :)

**Comment by usercao** [comment]
可以啊没问题，你在这个项目下面开个打赏吧。

**Comment by caoxiemeihao** [comment]
兄弟你的意思是这里要用 `require('@/assets/images/test/${xxx}.png')` 类似这种形式嘛

<img width="746" alt="image" src="https://user-images.githubusercontent.com/26263658/171076720-b3a6df82-e21b-4919-ab8e-55f66159425a.png">

**Comment by usercao** [comment]
是的，上面提到的`vite-plugin-require`就是不支持别名，其他的效果和`webpack`的`require()`还是相符的，上面的demo也可以拉下来做测试用。

**Comment by caoxiemeihao** [comment]
那个插件瞄了一眼，只做了 `require(id)` 的提升，且 `id` 只能用普通的字符串；  
就是说 `vite-plugin-dynamic-require` 要在此基础上要加两个功能：  
1. 要能支持 动态id(dynaimc-require)
2. 别名(alias)、`node_modules` 模块支持

得要花点时间的 🐌

**Comment by usercao** [comment]
👍支持，不过虽然她的文档中说`id`只能是普通字符串，但我实测模板字符串开发和打包后都是没问题的，你使用过`webpack`的`require()`动态导入静态资源吗？你们导入静态资源通常怎么做的？不会是在顶部`import`之后再在`tsx`中使用吧？这样例如一个活动页面图片很多岂不是导入代码爆炸？

**Comment by caoxiemeihao** [comment]
你真的以为 `require(id)` 是动态导入的，CJS 定义的 `require()` 是同步的；Webpack 碰到 `require()` 会穷举出所有的可能性，生成后的产物不见的多“优雅”！

你用翻译软件看看文档便知。  
https://webpack.js.org/guides/dependency-management/#require-with-expression

<img width="808" alt="image" src="https://user-images.githubusercontent.com/26263658/171084417-fde034fe-b97e-400e-9673-0cd78817154c.png">

**Comment by usercao** [comment]
看完文档发现以前的理解确实有误，想了解一下你在做导入图片的通常是怎样实现的？

**Comment by caoxiemeihao** [comment]
一样的，只能通过穷举将作用文件提前导入；其次维护一个键值对表做下运行时匹配即可

**Comment by usercao** [comment]
神速👍我试试

**Comment by usercao** [comment]
```js
import viteRequire from 'vite-require';

export default {
  vitePlugins: [viteRequire],
};
```
<img width="368" alt="image" src="https://user-images.githubusercontent.com/13760476/172287269-f6ee2b1a-736b-409a-b95e-273d2cc44c7f.png">

没有看到相关文档，猜测使用`require()`报错

**Comment by caoxiemeihao** [comment]
viteRequire()

**Comment by usercao** [comment]
> viteRequire()
<img width="677" alt="image" src="https://user-images.githubusercontent.com/13760476/172291948-1d76ccaf-8d0d-4cd3-8fd0-aaf2ad5c31f2.png">

<img width="929" alt="image" src="https://user-images.githubusercontent.com/13760476/172292048-a6c459f4-cbb4-4a8c-bb88-298e3108415b.png">

也试过，一是类型错误，二是启动报错

**Comment by caoxiemeihao** [comment]
你这还是那个 Demo？

**Comment by usercao** [comment]
> 你这还是那个 Demo？

是的

**Comment by caoxiemeihao** [comment]
[vite-require@v0.1.1](https://www.npmjs.com/package/vite-require)

**Comment by caoxiemeihao** [comment]
你确定？

**Comment by caoxiemeihao** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/26263658/172343537-a4c37913-d767-4570-ae5a-28cee9c734ba.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/26263658/172343599-14cf66ad-3a7e-405d-8802-47e606e4bce4.png">

**Comment by usercao** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/13760476/172346378-58dda999-3645-4214-be81-b129f1d98fd6.png">

我是本地测试发现有问题没提交代码

**Comment by usercao** [comment]
```css
background-image: url(${require('@/assets/images/test/test.png')});
```

<img width="457" alt="image" src="https://user-images.githubusercontent.com/13760476/172350574-5ab3ef50-720e-4d26-85df-0279aad289b0.png">


在css in js中使用会报错

**Comment by caoxiemeihao** [comment]
`vite-require@v0.1.2` has been released.

**Comment by usercao** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/13760476/173229834-ed88b6ca-7973-4c01-9b88-7a27e3752148.png">

新的报错

**Comment by caoxiemeihao** [comment]
> <img alt="image" width="834" src="https://user-images.githubusercontent.com/13760476/173229834-ed88b6ca-7973-4c01-9b88-7a27e3752148.png">
> 
> 新的报错

你确定这个和 `vite-require` 有关系？

**Comment by usercao** [comment]
是的，还是上面这个[Demo](https://github.com/usercao/ice-test)，变动只有更新`vite-require`版本
