### ISSUE TITLE
Internal server error: Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by vitorsemeano** [vite-plugin/vite-plugin-dynamic-import#53]
When upgrading from 1.2.7 to 1.3.x, I got the following error:

[vite] Internal server error: Cannot use 'import.meta' outside a module (1:0)

Further inspection, the error comes from using the lib acorn, saying that "import.meta" can't be used on scripts.

I am using a vite project with hmr. When running vite dev, vite will inject import.meta.hot in the compiled bundle.  es-module-lexer will read the bundle and extract all imports, including import.meta.*. When you call acorn parse, you don't specify the sourceType, and the default value to that is 'script'. When it catches 'import.meta', it will throw this error.

Reverting to 1.2.7 solves this problem.

Possible solution would be to pass sourceType value as option of acorn.

**Comment by caoxiemeihao** [comment]
sure right

**Comment by caoxiemeihao** [comment]
I still hope you provide a minimal reproduction repo :)

**Comment by vitorsemeano** [comment]
Hi, I see it's solved, but if you ever wanted to see the problem, here is the reproduction repo:

https://codesandbox.io/s/vite-react-forked-xw8suh

Thanks
