### ISSUE TITLE
when i use node_modules error will occur when starting

### ISSUE THREAD

**Issue by Miofly** [vite-plugin/vite-plugin-dynamic-import#56]
![image](https://github.com/vite-plugin/vite-plugin-dynamic-import/assets/42859910/74300bf9-4a7c-4c90-9c71-83dfc1553da6)
function is correct, is seem to import type error

repo link:https://github.com/Miofly/vue-admin-plus

**Comment by Miofly** [comment]
@caoxiemeihao 大佬这个插件还在维护吗

**Comment by caoxiemeihao** [comment]
在维护的，你这个 BUG 我给忘了
你这个复现 Demo 是不是有点大了
换个小点的

**Comment by Miofly** [comment]
> 在维护的，你这个 BUG 我给忘了 你这个复现 Demo 是不是有点大了 换个小点的

https://github.com/Miofly/demo-issue-template/tree/vite-import
这里是一个比较简单的demo，可能和typescipt 版本升级到了 5点几有关系
