### ISSUE TITLE
Please add a LICENSE if you are okay with people using this plugin

### ISSUE THREAD

**Issue by benelan** [vite-plugin/vite-plugin-dynamic-import#61]
Hi, thanks for your work on this plugin! If you're okay with people using it, can you please add a license so it can be done legally? See [GitHub's licensing documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) for more info, specifically:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

The MIT license is what people commonly use for open source projects like this, [including Vite itself](https://github.com/vitejs/vite/blob/main/LICENSE). The GitHub documentation has information about all of the license options if you'd prefer to use something else. Thanks!

**Comment by yejimeiming** [comment]
Right. All is OK!
