### ISSUE TITLE
re Disable dynamic import detection for one line or for whole project

### ISSUE THREAD

**Issue by b5414** [vite-plugin/vite-plugin-dynamic-import#73]
Hi, is this problem related or should be here as main? 

https://github.com/vitejs/vite/issues/16241

**Comment by yejimeiming** [comment]
Sorry, this is not what `vite-plugin-dynamic-import` should do.

**Comment by b5414** [comment]
@yejimeiming what do you mean? How can I solve this issue?

**Comment by yejimeiming** [comment]
Perhaps you should seek help from Vite.
